[GCC]drivers/soc/google: procfs_node: Set missing return type to int
Reported by GCC 12.2, fixes the following error

../drivers/soc/google/vh/kernel/sched/procfs_node.c:1254:9: error: return type defaults to 'int' [-Werror=return-type]
 1254 | static  pmu_poll_enable_show(struct seq_file *m, void *v)

Signed-off-by: Panchajanya1999 <kernel@panchajanya.dev>
(cherry picked from commit 460aab076fcc289541af4509382adca90a0c82d3)
(cherry picked from commit 236bc170755e7d5e4f8f03ca04b4f295838fdad3)
(cherry picked from commit 4cfef90b064ef21f9e217ed2bc6e136f0fa274c1)